import type { Achievement, AchievementCode } from "./types";

export const ACHIEVEMENTS: readonly Achievement[] = [
  {
    code: "first_steps",
    title: "First steps",
    description: "Completed onboarding and chose a path.",
    category: "beginnings",
    tier: "bronze",
    icon: "footsteps-outline",
    quote: {
      text: "And whoever takes Allah as an ally, then indeed, the party of Allah, they will be the predominant.",
      source: "Qur'an 5:56",
    },
  },
  {
    code: "first_log",
    title: "First salah logged",
    description: "Logged a prayer for the first time.",
    category: "beginnings",
    tier: "bronze",
    icon: "checkmark-circle-outline",
  },
  {
    code: "first_on_time",
    title: "On time",
    description: "Logged a prayer within its on-time window.",
    category: "beginnings",
    tier: "bronze",
    icon: "time-outline",
    quote: {
      text: "Indeed, prayer has been decreed upon the believers a decree of specified times.",
      source: "Qur'an 4:103",
    },
  },
  {
    code: "first_dhikr",
    title: "First remembrance",
    description: "Counted your first dhikr.",
    category: "beginnings",
    tier: "bronze",
    icon: "ellipse-outline",
  },
  {
    code: "perfect_day_1",
    title: "A complete day",
    description: "All five salah logged within their windows.",
    category: "salah",
    tier: "bronze",
    icon: "sunny-outline",
  },
  {
    code: "perfect_day_7",
    title: "Seven complete days",
    description: "Seven on-time days, lifetime.",
    category: "salah",
    tier: "silver",
    icon: "sunny-outline",
  },
  {
    code: "perfect_day_30",
    title: "Thirty complete days",
    description: "Thirty on-time days, lifetime.",
    category: "salah",
    tier: "gold",
    icon: "sunny",
  },
  {
    code: "streak_3",
    title: "Three-day streak",
    description: "Three full days of salah in a row.",
    category: "continuity",
    tier: "bronze",
    icon: "flame-outline",
  },
  {
    code: "streak_7",
    title: "Seven-day streak",
    description: "One week of complete salah.",
    category: "continuity",
    tier: "silver",
    icon: "flame-outline",
  },
  {
    code: "streak_30",
    title: "Thirty-day streak",
    description: "A month of complete salah.",
    category: "continuity",
    tier: "gold",
    icon: "flame-outline",
  },
  {
    code: "streak_100",
    title: "One hundred days",
    description: "One hundred days of complete salah.",
    category: "continuity",
    tier: "gold",
    icon: "flame",
  },
  {
    code: "streak_365",
    title: "A full year",
    description: "Three hundred and sixty-five days of complete salah.",
    category: "continuity",
    tier: "gold",
    icon: "flame",
    quote: {
      text: "The most beloved deeds to Allah are those done consistently, even if small.",
      source: "Bukhari 6464",
    },
  },
  {
    code: "fajr_streak_7",
    title: "Fajr for a week",
    description: "Logged Fajr on time, seven days running.",
    category: "fajr",
    tier: "silver",
    icon: "moon-outline",
    quote: {
      text: "The two units before Fajr are better than the world and what it contains.",
      source: "Muslim 725",
    },
  },
  {
    code: "fajr_streak_30",
    title: "Fajr for a month",
    description: "Logged Fajr on time, thirty days running.",
    category: "fajr",
    tier: "gold",
    icon: "moon",
  },
  {
    code: "pre_dawn_watcher",
    title: "Pre-dawn watcher",
    description:
      "Logged Fajr on time fourteen days within a three-week window.",
    category: "fajr",
    tier: "silver",
    icon: "moon-outline",
  },
  {
    code: "fajr_100",
    title: "Hundred dawns",
    description: "One hundred on-time Fajr prayers, lifetime.",
    category: "fajr",
    tier: "gold",
    icon: "moon",
    quote: {
      text: "Whoever prays Fajr is under the protection of Allah.",
      source: "Muslim 657",
    },
  },
  {
    code: "isha_streak_7",
    title: "A week of night",
    description: "Logged Isha on time, seven days running.",
    category: "night",
    tier: "silver",
    icon: "star-outline",
  },
  {
    code: "late_devotion",
    title: "Quiet hours",
    description: "Logged Isha after 10pm thirty times, lifetime.",
    category: "night",
    tier: "silver",
    icon: "star-outline",
  },
  {
    code: "night_complete_30",
    title: "Thirty nights",
    description: "Logged Isha on time thirty days in a row.",
    category: "night",
    tier: "gold",
    icon: "star",
  },
  {
    code: "dhikr_100",
    title: "One hundred dhikr",
    description: "Reached one hundred dhikr, lifetime.",
    category: "remembrance",
    tier: "bronze",
    icon: "ellipse-outline",
  },
  {
    code: "dhikr_1000",
    title: "One thousand dhikr",
    description: "Reached one thousand dhikr, lifetime.",
    category: "remembrance",
    tier: "silver",
    icon: "ellipse-outline",
  },
  {
    code: "dhikr_10000",
    title: "Ten thousand dhikr",
    description: "Reached ten thousand dhikr, lifetime.",
    category: "remembrance",
    tier: "gold",
    icon: "ellipse",
    quote: {
      text: "Remember Me; I will remember you.",
      source: "Qur'an 2:152",
    },
  },
  {
    code: "dhikr_100k",
    title: "One hundred thousand",
    description: "Reached one hundred thousand dhikr, lifetime.",
    category: "remembrance",
    tier: "gold",
    icon: "ellipse",
    quote: {
      text: "Those who believe and whose hearts find rest in the remembrance of Allah.",
      source: "Qur'an 13:28",
    },
  },
  {
    code: "qada_first",
    title: "Making up",
    description: "Logged your first qadā salah.",
    category: "mercy",
    tier: "bronze",
    icon: "refresh-outline",
  },
  {
    code: "qada_seven",
    title: "Seven made up",
    description: "Logged seven qadā salah, lifetime.",
    category: "mercy",
    tier: "silver",
    icon: "refresh-outline",
  },
  {
    code: "comeback",
    title: "Returning",
    description: "Resumed salah after a pause of seven days.",
    category: "mercy",
    tier: "silver",
    icon: "leaf-outline",
    quote: {
      text: "Allah loves those who turn to Him in repentance and loves those who purify themselves.",
      source: "Qur'an 2:222",
    },
  },
  {
    code: "gentle_return",
    title: "Returning, again",
    description: "Returned after a long pause for the third time.",
    category: "mercy",
    tier: "gold",
    icon: "leaf-outline",
  },
  {
    code: "jumuah_4",
    title: "Four Fridays",
    description: "Logged Dhuhr on time on four distinct Fridays.",
    category: "seasons",
    tier: "silver",
    icon: "sunny-outline",
  },
  {
    code: "jumuah_12",
    title: "A season of Fridays",
    description: "Logged Dhuhr on time on twelve distinct Fridays.",
    category: "seasons",
    tier: "gold",
    icon: "sunny",
  },
  {
    code: "sacred_month_day",
    title: "A sacred day",
    description: "Completed a full day of salah during a sacred month.",
    category: "seasons",
    tier: "bronze",
    icon: "moon-outline",
  },
  {
    code: "ramadan_complete",
    title: "A Ramadan kept",
    description: "Completed every day of Ramadan with all five salah.",
    category: "seasons",
    tier: "gold",
    icon: "moon",
    quote: {
      text: "The month of Ramadan, in which was revealed the Qur'an, a guidance for the people.",
      source: "Qur'an 2:185",
    },
  },
  {
    code: "all_bronze",
    title: "Every first step",
    description: "Unlocked every bronze achievement.",
    category: "reflection",
    tier: "silver",
    icon: "star-outline",
  },
  {
    code: "all_silver",
    title: "Every middle",
    description: "Unlocked every silver achievement.",
    category: "reflection",
    tier: "gold",
    icon: "star-outline",
  },
  {
    code: "all_gold",
    title: "Every summit",
    description: "Unlocked every gold achievement.",
    category: "reflection",
    tier: "gold",
    icon: "star",
  },
  {
    code: "complete",
    title: "The path walked",
    description: "Unlocked every achievement on the path.",
    category: "reflection",
    tier: "gold",
    icon: "trophy",
    quote: {
      text: "Whoever travels a path seeking knowledge, Allah makes easy for him a path to Paradise.",
      source: "Muslim 2699",
    },
  },
];

export const ACHIEVEMENT_CODES: readonly AchievementCode[] = ACHIEVEMENTS.map(
  (a) => a.code
);
