import type { Achievement, AchievementCode } from "./types";

export const ACHIEVEMENTS: readonly Achievement[] = [
  {
    code: "first_steps",
    title: "First steps",
    description: "Completed onboarding and chose a path.",
    category: "onboarding",
    tier: "bronze",
    icon: "footsteps-outline",
    quote: {
      text: "And whoever takes Allah as an ally, then indeed, the party of Allah, they will be the predominant.",
      source: "Qur'an 5:56",
    },
  },
  {
    code: "first_log",
    title: "First salah logged",
    description: "Logged a prayer for the first time.",
    category: "prayer",
    tier: "bronze",
    icon: "checkmark-circle-outline",
  },
  {
    code: "first_on_time",
    title: "On time",
    description: "Logged a prayer within its on-time window.",
    category: "prayer",
    tier: "bronze",
    icon: "time-outline",
    quote: {
      text: "Indeed, prayer has been decreed upon the believers a decree of specified times.",
      source: "Qur'an 4:103",
    },
  },
  {
    code: "streak_3",
    title: "Three-day streak",
    description: "Three full days of salah in a row.",
    category: "streak",
    tier: "bronze",
    icon: "flame-outline",
  },
  {
    code: "streak_7",
    title: "Seven-day streak",
    description: "One week of complete salah.",
    category: "streak",
    tier: "silver",
    icon: "flame-outline",
  },
  {
    code: "streak_30",
    title: "Thirty-day streak",
    description: "A month of complete salah.",
    category: "streak",
    tier: "gold",
    icon: "flame-outline",
  },
  {
    code: "streak_100",
    title: "One hundred days",
    description: "One hundred days of complete salah.",
    category: "streak",
    tier: "gold",
    icon: "flame",
  },
  {
    code: "perfect_day_1",
    title: "A complete day",
    description: "All five salah logged within their windows.",
    category: "prayer",
    tier: "bronze",
    icon: "sunny-outline",
  },
  {
    code: "perfect_day_7",
    title: "Seven complete days",
    description: "Seven on-time days, lifetime.",
    category: "prayer",
    tier: "silver",
    icon: "sunny-outline",
  },
  {
    code: "perfect_day_30",
    title: "Thirty complete days",
    description: "Thirty on-time days, lifetime.",
    category: "prayer",
    tier: "gold",
    icon: "sunny",
  },
  {
    code: "fajr_streak_7",
    title: "Fajr for a week",
    description: "Logged Fajr on time, seven days running.",
    category: "prayer",
    tier: "silver",
    icon: "moon-outline",
    quote: {
      text: "The two units before Fajr are better than the world and what it contains.",
      source: "Muslim 725",
    },
  },
  {
    code: "fajr_streak_30",
    title: "Fajr for a month",
    description: "Logged Fajr on time, thirty days running.",
    category: "prayer",
    tier: "gold",
    icon: "moon",
  },
  {
    code: "dhikr_100",
    title: "One hundred dhikr",
    description: "Reached one hundred dhikr, lifetime.",
    category: "dhikr",
    tier: "bronze",
    icon: "ellipse-outline",
  },
  {
    code: "dhikr_1000",
    title: "One thousand dhikr",
    description: "Reached one thousand dhikr, lifetime.",
    category: "dhikr",
    tier: "silver",
    icon: "ellipse-outline",
  },
  {
    code: "dhikr_10000",
    title: "Ten thousand dhikr",
    description: "Reached ten thousand dhikr, lifetime.",
    category: "dhikr",
    tier: "gold",
    icon: "ellipse",
    quote: {
      text: "Remember Me; I will remember you.",
      source: "Qur'an 2:152",
    },
  },
  {
    code: "qada_first",
    title: "Making up",
    description: "Logged your first qadā salah.",
    category: "recovery",
    tier: "bronze",
    icon: "refresh-outline",
  },
  {
    code: "comeback",
    title: "Returning",
    description: "Resumed salah after a pause of seven days.",
    category: "recovery",
    tier: "silver",
    icon: "leaf-outline",
    quote: {
      text: "Allah loves those who turn to Him in repentance and loves those who purify themselves.",
      source: "Qur'an 2:222",
    },
  },
];

export const ACHIEVEMENT_CODES: readonly AchievementCode[] = ACHIEVEMENTS.map(
  (a) => a.code
);
