import {
  index,
  integer,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// Better Auth tables (singular: user/account/session/verification) live in their
// own file, generated by `@better-auth/cli generate`. Re-exported here so the
// drizzle adapter + drizzle-kit see the full schema. Regenerate after auth
// config changes; never hand-edit auth-schema.ts.
export { account, session, user, verification } from "@/db/auth-schema";

import { account, session, user, verification } from "@/db/auth-schema";

// Field-shape unions mirror packages/core validators (users, shieldSelection,
// subscriptions, prayer). Validation stays in the route layer (zod, reusing core);
// these `$type` annotations only document/strengthen the column types.
type Gender = "male" | "female";
type Madhab = "hanafi" | "shafii" | "maliki" | "hanbali" | "none";
type Consistency = "never" | "sometimes" | "most" | "all";
type Struggle = "phone" | "forgetting" | "fajr" | "khushu";
type Goal = "all-five" | "khushu" | "phone-addiction" | "fajr";
type CalcMethod =
  | "isna"
  | "mwl"
  | "umm-al-qura"
  | "egyptian"
  | "karachi"
  | "custom";
type Strictness = "adhan-iqama" | "full-window" | "custom";
export interface PrayersToLock {
  asr: boolean;
  dhuhr: boolean;
  fajr: boolean;
  isha: boolean;
  maghrib: boolean;
}

type ProductId = "yearly" | "monthly" | "family" | "lifetime";
type SubscriptionStatus = "active" | "inactive" | "canceled" | "past_due";
type SubscriptionSource = "mock" | "polar" | "revenuecat";
type RevenueCatStore =
  | "app_store"
  | "play_store"
  | "stripe"
  | "promotional"
  | "mac_app_store"
  | "amazon";
type RevenueCatPeriodType = "normal" | "trial" | "intro";

type PrayerName = "fajr" | "dhuhr" | "asr" | "maghrib" | "isha";
type PrayerLogStatus = "early" | "on_time" | "late" | "qada" | "missed";

export type PrayerSource = "aladhan" | "adhan-js" | "hybrid";
type PrayerPrimarySource = "aladhan" | "adhan-js";
export interface PrayerTimingDay {
  date: string;
  hijriDate?: string;
  location: { latitude: number; longitude: number };
  method: number;
  school: number;
  source: PrayerSource;
  timezone: string;
  timings: {
    fajr: string;
    sunrise: string;
    dhuhr: string;
    asr: string;
    maghrib: string;
    isha: string;
  };
}

const uuid = () => crypto.randomUUID();

export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    name: text("name"),
    gender: text("gender").$type<Gender>(),
    madhab: text("madhab").$type<Madhab>(),
    consistency: text("consistency").$type<Consistency>(),
    struggle: text("struggle").$type<Struggle>(),
    goal: text("goal").$type<Goal>(),
    calcMethod: text("calcMethod").$type<CalcMethod>(),
    strictness: text("strictness").$type<Strictness>(),
    locationGranted: integer("locationGranted", { mode: "boolean" }),
    notifGranted: integer("notifGranted", { mode: "boolean" }),
    prayersToLock: text("prayersToLock", {
      mode: "json",
    }).$type<PrayersToLock>(),
    completedAt: text("completedAt"),
    // Was Convex `v.id("_storage")`; now the R2 object key for the avatar.
    image: text("image"),
    activePrayerLocationId: text("activePrayerLocationId"),
  },
  (t) => [index("users_by_authUserId").on(t.authUserId)]
);

export const subscriptions = sqliteTable(
  "subscriptions",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId"),
    customerEmail: text("customerEmail"),
    productId: text("productId").notNull().$type<ProductId>(),
    status: text("status").notNull().$type<SubscriptionStatus>(),
    source: text("source").notNull().$type<SubscriptionSource>(),
    claimedAt: text("claimedAt"),
    activatedAt: text("activatedAt"),
    updatedAt: text("updatedAt"),
    expiresAt: text("expiresAt"),
    polarCustomerId: text("polarCustomerId"),
    polarProductId: text("polarProductId"),
    polarOrderId: text("polarOrderId"),
    rcAppUserId: text("rcAppUserId"),
    rcOriginalAppUserId: text("rcOriginalAppUserId"),
    rcProductIdentifier: text("rcProductIdentifier"),
    rcEntitlementId: text("rcEntitlementId"),
    rcStore: text("rcStore").$type<RevenueCatStore>(),
    rcPeriodType: text("rcPeriodType").$type<RevenueCatPeriodType>(),
    rcWillRenew: integer("rcWillRenew", { mode: "boolean" }),
    rcLatestPurchaseAt: text("rcLatestPurchaseAt"),
  },
  (t) => [
    index("subscriptions_by_authUserId").on(t.authUserId),
    index("subscriptions_by_authUserId_status").on(t.authUserId, t.status),
    index("subscriptions_by_customerEmail").on(t.customerEmail),
    uniqueIndex("subscriptions_by_polarOrderId").on(t.polarOrderId),
    index("subscriptions_by_polarCustomerId").on(t.polarCustomerId),
    index("subscriptions_by_rcAppUserId").on(t.rcAppUserId),
  ]
);

export const polarOrders = sqliteTable(
  "polarOrders",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId"),
    polarOrderId: text("polarOrderId").notNull(),
    polarCustomerId: text("polarCustomerId"),
    customerEmail: text("customerEmail").notNull(),
    customerName: text("customerName"),
    productId: text("productId"),
    totalAmount: integer("totalAmount", { mode: "number" }).notNull(),
    currency: text("currency").notNull(),
    invoiceNumber: text("invoiceNumber"),
    eventType: text("eventType").notNull(),
    receivedAt: text("receivedAt").notNull(),
    confirmationEmailQueuedAt: text("confirmationEmailQueuedAt"),
    confirmedEmailAt: text("confirmedEmailAt"),
    raw: text("raw", { mode: "json" }).$type<unknown>(),
  },
  (t) => [
    uniqueIndex("polarOrders_by_polarOrderId").on(t.polarOrderId),
    index("polarOrders_by_customerEmail").on(t.customerEmail),
    index("polarOrders_by_polarCustomerId").on(t.polarCustomerId),
  ]
);

export const prayerTimeCaches = sqliteTable(
  "prayerTimeCaches",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    userId: text("userId"),
    cacheKey: text("cacheKey").notNull(),
    userCacheKey: text("userCacheKey").notNull(),
    latitude: real("latitude").notNull(),
    longitude: real("longitude").notNull(),
    latitudeRounded: real("latitudeRounded").notNull(),
    longitudeRounded: real("longitudeRounded").notNull(),
    timezone: text("timezone").notNull(),
    countryCode: text("countryCode"),
    city: text("city"),
    method: integer("method", { mode: "number" }).notNull(),
    school: integer("school", { mode: "number" }).notNull(),
    latitudeAdjustmentMethod: integer("latitudeAdjustmentMethod", {
      mode: "number",
    }),
    midnightMode: integer("midnightMode", { mode: "number" }),
    tune: text("tune"),
    startDate: text("startDate").notNull(),
    endDate: text("endDate").notNull(),
    days: integer("days", { mode: "number" }).notNull(),
    source: text("source").notNull().$type<PrayerSource>(),
    primarySource: text("primarySource").notNull().$type<PrayerPrimarySource>(),
    fallbackSource: text("fallbackSource").$type<"adhan-js">(),
    // Large blob; KV holds the hot copy (§5), D1 keeps the durable record.
    timings: text("timings", { mode: "json" }).$type<PrayerTimingDay[]>(),
    comparison: text("comparison", { mode: "json" }).$type<unknown>(),
    raw: text("raw", { mode: "json" }).$type<unknown>(),
    generatedAt: integer("generatedAt", { mode: "number" }).notNull(),
    expiresAt: integer("expiresAt", { mode: "number" }).notNull(),
    createdAt: integer("createdAt", { mode: "number" }).notNull(),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [
    index("prayerTimeCaches_by_cacheKey").on(t.cacheKey),
    index("prayerTimeCaches_by_userCacheKey").on(t.userCacheKey),
    index("prayerTimeCaches_by_userId").on(t.userId),
    index("prayerTimeCaches_by_user_updated").on(t.userId, t.updatedAt),
    index("prayerTimeCaches_by_expiry").on(t.expiresAt),
  ]
);

export const prayerLogs = sqliteTable(
  "prayerLogs",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    date: text("date").notNull(),
    prayer: text("prayer").notNull().$type<PrayerName>(),
    status: text("status").notNull().$type<PrayerLogStatus>(),
    prayedAt: integer("prayedAt", { mode: "number" }),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [
    uniqueIndex("prayerLogs_by_user_date_prayer").on(
      t.authUserId,
      t.date,
      t.prayer
    ),
    index("prayerLogs_by_user_updated").on(t.authUserId, t.updatedAt),
  ]
);

export const shieldSelection = sqliteTable(
  "shieldSelection",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    iosSelectionData: text("iosSelectionData"),
    iosItemCount: integer("iosItemCount", { mode: "number" }),
    androidPackageNames: text("androidPackageNames", { mode: "json" }).$type<
      string[]
    >(),
    windows: text("windows", { mode: "json" }).notNull().$type<PrayerName[]>(),
    enabled: integer("enabled", { mode: "boolean" }).notNull(),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [uniqueIndex("shieldSelection_by_user").on(t.authUserId)]
);

export const dhikrDaily = sqliteTable(
  "dhikrDaily",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    date: text("date").notNull(),
    count: integer("count", { mode: "number" }).notNull(),
    target: integer("target", { mode: "number" }).notNull(),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [uniqueIndex("dhikrDaily_by_user_date").on(t.authUserId, t.date)]
);

export const dhikrAggregate = sqliteTable(
  "dhikrAggregate",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    total: integer("total", { mode: "number" }).notNull(),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [uniqueIndex("dhikrAggregate_by_user").on(t.authUserId)]
);

export const userLocations = sqliteTable(
  "userLocations",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    name: text("name").notNull(),
    latitude: real("latitude").notNull(),
    longitude: real("longitude").notNull(),
    timezone: text("timezone").notNull(),
    city: text("city"),
    countryCode: text("countryCode"),
    createdAt: integer("createdAt", { mode: "number" }).notNull(),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [index("userLocations_by_user").on(t.authUserId)]
);

export const userAchievements = sqliteTable(
  "userAchievements",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    code: text("code").notNull(),
    unlockedAt: integer("unlockedAt", { mode: "number" }).notNull(),
    seenAt: integer("seenAt", { mode: "number" }),
  },
  (t) => [
    index("userAchievements_by_user").on(t.authUserId),
    uniqueIndex("userAchievements_by_user_code").on(t.authUserId, t.code),
    index("userAchievements_by_user_seen").on(t.authUserId, t.seenAt),
  ]
);

export const userAchievementCounters = sqliteTable(
  "userAchievementCounters",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    authUserId: text("authUserId").notNull(),
    countablePrayerLogs: integer("countablePrayerLogs", {
      mode: "number",
    }).notNull(),
    fajrOnTimePrayerLogs: integer("fajrOnTimePrayerLogs", {
      mode: "number",
    }).notNull(),
    onTimePrayerLogs: integer("onTimePrayerLogs", { mode: "number" }).notNull(),
    qadaPrayerLogs: integer("qadaPrayerLogs", { mode: "number" }).notNull(),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [uniqueIndex("userAchievementCounters_by_user").on(t.authUserId)]
);

export const appConfig = sqliteTable("appConfig", {
  id: text("id").primaryKey().$defaultFn(uuid),
  minSupportedVersion: text("minSupportedVersion").notNull(),
  iosStoreUrl: text("iosStoreUrl").notNull(),
  updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
});

type EmailQueueStatus = "queued" | "sent" | "failed";

// Durable transactional-email queue. Replaces @convex-dev/resend's built-in
// queue + retry (the raw Resend SDK has neither). A Workers cron sweeps `queued`
// rows whose nextAttemptAt is due (§9). `dedupeKey` makes enqueue idempotent so
// a webhook retry (e.g. a duplicate Polar order) never double-sends.
export const emailQueue = sqliteTable(
  "emailQueue",
  {
    id: text("id").primaryKey().$defaultFn(uuid),
    dedupeKey: text("dedupeKey"),
    to: text("to").notNull(),
    subject: text("subject").notNull(),
    html: text("html").notNull(),
    text: text("text"),
    status: text("status").notNull().$type<EmailQueueStatus>(),
    attempts: integer("attempts", { mode: "number" }).notNull(),
    lastError: text("lastError"),
    providerId: text("providerId"),
    nextAttemptAt: integer("nextAttemptAt", { mode: "number" }).notNull(),
    sentAt: integer("sentAt", { mode: "number" }),
    createdAt: integer("createdAt", { mode: "number" }).notNull(),
    updatedAt: integer("updatedAt", { mode: "number" }).notNull(),
  },
  (t) => [
    uniqueIndex("emailQueue_by_dedupeKey").on(t.dedupeKey),
    index("emailQueue_by_status_next").on(t.status, t.nextAttemptAt),
    index("emailQueue_by_providerId").on(t.providerId),
  ]
);

export const schema = {
  users,
  subscriptions,
  polarOrders,
  prayerTimeCaches,
  prayerLogs,
  shieldSelection,
  dhikrDaily,
  dhikrAggregate,
  userLocations,
  userAchievements,
  userAchievementCounters,
  appConfig,
  emailQueue,
  user,
  account,
  session,
  verification,
};
